[client]
gatherUsageStats = false

[server]
headless = true
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[logger]
level = "info"

[client]
showErrorDetails = false
allowRunOnSave = true
