[client]
headless = true
runOnSave = true
port = 8501
showErrorDetails = true

[server]
headless = true
port = 8501
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false
